//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectroEshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingAddress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BillingAddress()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int billing_id { get; set; }
        public string billing_firstName { get; set; }
        public string billing_lastName { get; set; }
        public string billing_email { get; set; }
        public string billing_address { get; set; }
        public string billing_city { get; set; }
        public string billing_country { get; set; }
        public Nullable<System.DateTime> billing_createDate { get; set; }
        public string billing_zipCode { get; set; }
        public string billing_telephone { get; set; }
        public string billing_note { get; set; }
        public string fk_user_id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
