//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectroEshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemOrder
    {
        public int item_id { get; set; }
        public Nullable<int> item_quantity { get; set; }
        public Nullable<int> item_discount { get; set; }
        public Nullable<decimal> item_quantityPrice { get; set; }
        public int fk_product_id { get; set; }
        public int fk_order_id { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
