//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectroEshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Newsletter
    {
        public int newsletter_id { get; set; }
        public string newsletter_email { get; set; }
        public Nullable<byte> newsletter_order { get; set; }
    }
}
