//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectroEshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.ItemsOrders = new HashSet<ItemOrder>();
        }
    
        public int order_id { get; set; }
        public Nullable<System.DateTime> order_createDate { get; set; }
        public Nullable<decimal> order_totalPrice { get; set; }
        public Nullable<decimal> order_shippingPrice { get; set; }
        public string order_status { get; set; }
        public Nullable<int> fk_billing_id { get; set; }
        public string fk_user_id { get; set; }
        public Nullable<int> fk_shipping_id { get; set; }
    
        public virtual AdditionalShippingAddress AdditionalShippingAddress { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual BillingAddress BillingAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemOrder> ItemsOrders { get; set; }
    }
}
