//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectroEshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public int photo_id { get; set; }
        public string photo_name { get; set; }
        public string photo_alter { get; set; }
        public Nullable<int> fk_product_id { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
