//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectroEshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ItemsOrders = new HashSet<ItemOrder>();
            this.Photos = new HashSet<Photo>();
            this.Reviewers = new HashSet<Reviewer>();
        }
    
        public int product_id { get; set; }
        public string product_name { get; set; }
        public string product_model { get; set; }
        public string product_description { get; set; }
        public Nullable<int> product_quantity { get; set; }
        public Nullable<decimal> product_price { get; set; }
        public Nullable<int> product_discount { get; set; }
        public string product_mainPhoto { get; set; }
        public Nullable<System.DateTime> product_createDate { get; set; }
        public Nullable<System.DateTime> product_expiredDate { get; set; }
        public string product_size { get; set; }
        public string product_color { get; set; }
        public Nullable<int> product_soldQuantity { get; set; }
        public Nullable<int> fk_brand_id { get; set; }
        public Nullable<int> fk_category_id { get; set; }
        public Nullable<decimal> avg_rating { get; set; }
        public Nullable<decimal> product_discountprice { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemOrder> ItemsOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photo> Photos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reviewer> Reviewers { get; set; }
    }
}
