//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectroEshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviewer
    {
        public int reviewer_id { get; set; }
        public string reviewer_name { get; set; }
        public string reviewer_email { get; set; }
        public string reviewer_comment { get; set; }
        public Nullable<System.DateTime> reviewer_date { get; set; }
        public Nullable<byte> reviewer_rating { get; set; }
        public Nullable<int> fk_product_id { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
